# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/LinkPilot
spring.datasource.username=postgres
spring.datasource.password=Devraj@999
spring.jpa.hibernate.ddl-auto=update

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379